name: Executes the e2e tests on pull request
on:
  push:
    branches:
      - main
jobs:
  execute_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out on current change
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Install Firebase Tools globally
        run: npm install firebase-tools
      - name: Run e2e tests
        run: firebase emulators:exec "npm run test"