name: Executes the e2e tests on pull request
on: pull_request
jobs:
  execute_e2e_tests:
    runs-on: ubuntu-tatest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: npm ci && npm run build
      - run: npm install -g firebase-tools
      - run: firebase emulators:exec "npm run test"