name: Executes the e2e tests on pull request
on: [push]
jobs:
  execute_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out on current change
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Fix npm bug
        run: sudo chown -R 65534:121 "/root/.npm"
      - name: Install Firebase Tools globally
        run: sudo npm install -g firebase-tools
      - name: Alias firebase command
        run: firebase emulators:exec "npm run test"
